# Generated by Django 2.1.7 on 2019-08-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190817_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_follow',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Follow', verbose_name='フォロー'),
        ),
    ]
