# Generated by Django 2.1.7 on 2019-08-14 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, verbose_name='商品カテゴリ')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='DM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='メッセージ本文')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='タイトル')),
                ('text', models.TextField(blank=True, verbose_name='本文')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image01', stdimage.models.StdImageField(blank=True, upload_to='service/', verbose_name='サムネイル')),
                ('image02', stdimage.models.StdImageField(blank=True, upload_to='service/', verbose_name='サムネイル')),
                ('image03', stdimage.models.StdImageField(blank=True, upload_to='service/', verbose_name='サムネイル')),
                ('image04', stdimage.models.StdImageField(blank=True, upload_to='service/', verbose_name='サムネイル')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='タイトル')),
                ('text', models.TextField(blank=True, verbose_name='本文')),
                ('delivery_date', models.CharField(blank=True, choices=[('即日', '即日出荷'), ('1〜2営業日', '1〜2営業日出荷'), ('3〜4営業日', '3〜4営業日出荷'), ('4〜6営業日', '4〜6営業日出荷'), ('7営業日以降', '7営業日以降出荷')], max_length=15, verbose_name='出荷日')),
                ('rank', models.CharField(blank=True, choices=[('Sランク', 'S'), ('Aランク', 'A'), ('Bランク', 'B'), ('Cランク', 'C')], max_length=15, verbose_name='商品ランク')),
                ('unit', models.CharField(blank=True, choices=[('kg', 'kg'), ('個', '個')], max_length=15, verbose_name='単位')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='金額')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='my_apps.Category', verbose_name='商品カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='一言')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags_name', models.CharField(max_length=200, verbose_name='商品タグ')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(blank=True, to='my_apps.Tags', verbose_name='商品タグ'),
        ),
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
