# Generated by Django 2.1.7 on 2019-08-20 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecomments',
            name='post',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.PROTECT, to='my_apps.Service', verbose_name='紐づく記事'),
            preserve_default=False,
        ),
    ]
